use std::fmt::Write;
use tessera_artifacts::Artifact;
use tessera_citations::citation::Citation;

pub fn export_html(artifact: &Artifact, citations: &[Citation]) -> String {
    let mut output = String::new();

    output.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    output.push_str("  <meta charset=\"UTF-8\">\n");
    output
        .push_str("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    let _ = writeln!(output, "  <title>{}</title>", escape_html(&artifact.title));
    output.push_str("  <style>\n");
    output.push_str("    body { font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; color: #4B5563; }\n");
    output.push_str("    h1 { color: #111827; }\n");
    output.push_str("    .citation { background: #F5F3FF; border-radius: 8px; padding: 1rem; margin: 0.5rem 0; }\n");
    output.push_str("    .citation-title { font-weight: 600; color: #7C3AED; }\n");
    output.push_str("    .citation-meta { font-size: 0.875rem; color: #6B7280; }\n");
    output.push_str("    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #E5E7EB; font-size: 0.875rem; color: #9CA3AF; }\n");
    output.push_str("  </style>\n</head>\n<body>\n");

    let _ = writeln!(output, "  <h1>{}</h1>", escape_html(&artifact.title));

    if !artifact.content.is_empty() {
        let html_content = content_to_html(&artifact.content);
        let _ = write!(
            output,
            "  <div class=\"content\">\n{html_content}  </div>\n"
        );
    }

    if !citations.is_empty() {
        output.push_str("  <hr>\n  <h2>Sources</h2>\n");
        for citation in citations {
            output.push_str("  <div class=\"citation\">\n");
            let _ = writeln!(
                output,
                "    <div class=\"citation-title\">{}</div>",
                escape_html(&citation.source_title)
            );
            let _ = write!(
                output,
                "    <div class=\"citation-meta\">Used for: {} | Confidence: {:.0}%",
                escape_html(&citation.used_for),
                citation.confidence * 100.0
            );
            if let Some(page) = citation.page {
                let _ = write!(output, " | Page: {page}");
            }
            output.push_str("</div>\n");
            let _ = writeln!(
                output,
                "    <div class=\"citation-meta\">{}</div>",
                escape_html(&citation.source_uri)
            );
            output.push_str("  </div>\n");
        }
    }

    let _ = writeln!(
        output,
        "  <div class=\"footer\">Generated by Tessera — {}</div>",
        artifact.updated_at.format("%Y-%m-%d %H:%M UTC")
    );

    output.push_str("</body>\n</html>\n");
    output
}

fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn content_to_html(content: &str) -> String {
    let mut html = String::new();
    let mut in_paragraph = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            if in_paragraph {
                html.push_str("    </p>\n");
                in_paragraph = false;
            }
            continue;
        }

        if let Some(heading) = trimmed.strip_prefix("## ") {
            if in_paragraph {
                html.push_str("    </p>\n");
                in_paragraph = false;
            }
            let _ = writeln!(html, "    <h2>{}</h2>", escape_html(heading));
        } else if let Some(heading) = trimmed.strip_prefix("### ") {
            if in_paragraph {
                html.push_str("    </p>\n");
                in_paragraph = false;
            }
            let _ = writeln!(html, "    <h3>{}</h3>", escape_html(heading));
        } else if let Some(item) = trimmed.strip_prefix("- ") {
            if in_paragraph {
                html.push_str("    </p>\n");
                in_paragraph = false;
            }
            let _ = writeln!(html, "    <li>{}</li>", escape_html(item));
        } else if in_paragraph {
            html.push(' ');
            html.push_str(&escape_html(trimmed));
        } else {
            html.push_str("    <p>");
            in_paragraph = true;
            html.push_str(&escape_html(trimmed));
        }
    }

    if in_paragraph {
        html.push_str("</p>\n");
    }

    html
}

#[cfg(test)]
mod tests {
    use super::*;
    use tessera_artifacts::Artifact;
    use tessera_citations::citation::Citation;
    use tessera_core::{ArtifactType, SourceId, SourceType};

    #[test]
    fn export_basic_html() {
        let mut artifact = Artifact::new("Test PRD".to_string(), ArtifactType::Document, None);
        artifact.update_content("## Problem\n\nThe problem is X.".to_string());

        let html = export_html(&artifact, &[]);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<title>Test PRD</title>"));
        assert!(html.contains("<h1>Test PRD</h1>"));
        assert!(html.contains("<h2>Problem</h2>"));
        assert!(html.contains("The problem is X."));
    }

    #[test]
    fn export_html_with_citations() {
        let artifact = Artifact::new("Report".to_string(), ArtifactType::Document, None);
        let citations = vec![Citation::new(
            SourceId::new(),
            SourceType::LocalFile,
            "quarterly.pdf".to_string(),
            "file:///quarterly.pdf".to_string(),
            "hash1".to_string(),
            "file_hash1".to_string(),
            "Revenue figures".to_string(),
            0.88,
        )];

        let html = export_html(&artifact, &citations);
        assert!(html.contains("quarterly.pdf"));
        assert!(html.contains("Revenue figures"));
        assert!(html.contains("88%"));
    }

    #[test]
    fn html_escapes_special_chars() {
        let artifact = Artifact::new(
            "<script>alert('xss')</script>".to_string(),
            ArtifactType::Document,
            None,
        );
        let html = export_html(&artifact, &[]);
        assert!(!html.contains("<script>"));
        assert!(html.contains("&lt;script&gt;"));
    }
}
