use std::fmt::Write;
use tessera_artifacts::Artifact;
use tessera_citations::citation::Citation;

pub fn export_markdown(artifact: &Artifact, citations: &[Citation]) -> String {
    let mut output = String::new();

    let _ = writeln!(output, "# {}\n", artifact.title);

    if !artifact.content.is_empty() {
        output.push_str(&artifact.content);
        output.push_str("\n\n");
    }

    if !citations.is_empty() {
        output.push_str("---\n\n## Sources\n\n");
        for (i, citation) in citations.iter().enumerate() {
            let _ = writeln!(
                output,
                "{}. **{}** — {}",
                i + 1,
                citation.source_title,
                citation.used_for
            );
            if let Some(page) = citation.page {
                let _ = writeln!(output, "   Page: {page}");
            }
            let _ = writeln!(output, "   Confidence: {:.0}%", citation.confidence * 100.0);
            let _ = writeln!(output, "   URI: {}\n", citation.source_uri);
        }
    }

    let _ = writeln!(
        output,
        "---\n\n*Generated by Tessera — {}*",
        artifact.updated_at.format("%Y-%m-%d %H:%M UTC")
    );

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use tessera_artifacts::Artifact;
    use tessera_citations::citation::Citation;
    use tessera_core::{ArtifactType, SourceId, SourceType};

    #[test]
    fn export_basic_document() {
        let mut artifact = Artifact::new("Test PRD".to_string(), ArtifactType::Document, None);
        artifact.update_content(
            "## Problem\n\nThe problem is X.\n\n## Solution\n\nThe solution is Y.".to_string(),
        );

        let md = export_markdown(&artifact, &[]);
        assert!(md.contains("# Test PRD"));
        assert!(md.contains("The problem is X"));
        assert!(md.contains("Generated by Tessera"));
    }

    #[test]
    fn export_with_citations() {
        let artifact = Artifact::new("Report".to_string(), ArtifactType::Document, None);
        let citations = vec![Citation::new(
            SourceId::new(),
            SourceType::LocalFile,
            "Brief.pdf".to_string(),
            "file:///brief.pdf".to_string(),
            "hash1".to_string(),
            "Problem Statement".to_string(),
            0.92,
        )
        .with_page(4)];

        let md = export_markdown(&artifact, &citations);
        assert!(md.contains("## Sources"));
        assert!(md.contains("Brief.pdf"));
        assert!(md.contains("Page: 4"));
        assert!(md.contains("92%"));
    }
}
