//! Edge-case integration tests for the export engine.
//!
//! The inline unit tests in `src/*.rs` cover happy-path output shape;
//! the smoke suite at `tests/phase_smoke_export.rs` verifies that the
//! eight shipping format functions exist and aren't stubbed. This file
//! covers the *boundary* conditions that real users hit and that the
//! happy-path tests miss:
//!
//! * Empty artifacts (no body, no citations).
//! * Very long content (10k-line body that must not blow the stack).
//! * Unicode payloads (CJK, emoji, RTL Hebrew, combining marks,
//!   zero-width joiners, control characters that must NOT be smuggled
//!   into output).
//! * Mermaid edge cases the inline parser tests don't combine:
//!   adjacent blocks separated only by a newline, blocks at the very
//!   start/end of content, long DSL bodies, multiple diagram-type
//!   markers in the same artifact.
//! * Evidence pack edge cases: empty-citation list (must still
//!   produce a valid ZIP with `citations.json` = `[]`), duplicate
//!   source ids across many citations (must produce ONE source file
//!   per id, not N), Unicode source titles round-trip cleanly.
//!
//! Every test asserts a specific, falsifiable property of the output —
//! a stub returning `Default::default()` would fail every assertion
//! here.

use std::fmt::Write;
use std::io::Read;

use tessera_artifacts::Artifact;
use tessera_citations::citation::Citation;
use tessera_core::{ArtifactType, SourceId, SourceType};

use tessera_export::csv::export_csv;
use tessera_export::evidence_pack::build_evidence_pack;
use tessera_export::html::export_html;
use tessera_export::markdown::export_markdown;
use tessera_export::mermaid;

fn citation_for(source_id: SourceId, title: &str, used_for: &str) -> Citation {
    Citation::new(
        source_id,
        SourceType::LocalFile,
        title.to_string(),
        format!("file:///tessera/{}", title.replace(' ', "_")),
        blake3::hash(format!("chunk-{title}").as_bytes())
            .to_hex()
            .to_string(),
        blake3::hash(format!("file-{title}").as_bytes())
            .to_hex()
            .to_string(),
        used_for.to_string(),
        0.87,
    )
}

// -----------------------------------------------------------------------------
// Empty artifacts
// -----------------------------------------------------------------------------

#[test]
fn markdown_empty_artifact_renders_title_and_footer_only() {
    // No content, no citations — the renderer should still produce a
    // valid Markdown document with the title heading and the
    // "Generated by Tessera" footer.
    let artifact = Artifact::new("Empty Doc".into(), ArtifactType::Document, None);
    let out = export_markdown(&artifact, &[]);
    assert!(
        out.starts_with("# Empty Doc\n"),
        "expected title at top, got:\n{out}",
    );
    assert!(
        out.contains("Generated by Tessera"),
        "expected footer, got:\n{out}",
    );
    // The "## Sources" header must NOT be present when citations are empty.
    assert!(
        !out.contains("## Sources"),
        "empty citations must not render the Sources header, got:\n{out}",
    );
}

#[test]
fn html_empty_artifact_emits_valid_html_skeleton() {
    let artifact = Artifact::new("Empty HTML".into(), ArtifactType::Document, None);
    let out = export_html(&artifact, &[]);
    assert!(
        out.starts_with("<!DOCTYPE html>"),
        "expected DOCTYPE at top, got:\n{out}",
    );
    assert!(out.contains("<title>Empty HTML</title>"));
    assert!(
        out.contains("<h1>Empty HTML</h1>"),
        "expected H1 heading, got:\n{out}",
    );
    assert!(
        out.trim_end().ends_with("</html>"),
        "expected closing </html>, got:\n{out}",
    );
    // No mermaid runtime should be emitted for empty content.
    assert!(
        !out.contains("https://cdn.jsdelivr.net/npm/mermaid"),
        "empty content must NOT pull in the mermaid CDN, got:\n{out}",
    );
}

#[test]
fn csv_empty_artifact_emits_only_metadata_header_and_row() {
    let artifact = Artifact::new("Empty CSV".into(), ArtifactType::Sheet, None);
    let out = export_csv(&artifact, &[]);
    assert!(out.contains("title,type,version,created_at,updated_at"));
    assert!(out.contains("Empty CSV"));
    // The citation header must NOT be present.
    assert!(
        !out.contains("citation_id,source_title"),
        "empty citations must not emit the citation header, got:\n{out}",
    );
}

// -----------------------------------------------------------------------------
// Very long content
// -----------------------------------------------------------------------------

#[test]
fn markdown_very_long_content_does_not_overflow() {
    // 10k short paragraphs — well past any reasonable stack frame /
    // small-buffer optimisation boundary. The exporter must produce
    // output whose length is monotonically related to the input.
    let mut content = String::new();
    for i in 0..10_000 {
        writeln!(content, "Paragraph {i} body text.\n").unwrap();
    }
    let mut artifact = Artifact::new("Long Doc".into(), ArtifactType::Document, None);
    artifact.update_content(content.clone());

    let out = export_markdown(&artifact, &[]);
    // First and last paragraphs survive the round trip.
    assert!(
        out.contains("Paragraph 0 body text."),
        "expected first paragraph in output",
    );
    assert!(
        out.contains("Paragraph 9999 body text."),
        "expected last paragraph in output",
    );
    // Output is at least as long as the input (excluding the title /
    // footer scaffolding).
    assert!(
        out.len() > content.len(),
        "expected output >= input length, got out.len()={} input.len()={}",
        out.len(),
        content.len(),
    );
}

#[test]
fn html_very_long_content_emits_each_paragraph_separately() {
    // 1k paragraphs is enough to verify the paragraph loop in
    // `emit_text_segment` doesn't drop or merge anything.
    let mut content = String::new();
    for i in 0..1_000 {
        writeln!(content, "Paragraph {i} body.\n").unwrap();
    }
    let mut artifact = Artifact::new("Long HTML".into(), ArtifactType::Document, None);
    artifact.update_content(content);

    let out = export_html(&artifact, &[]);
    let p_count = out.matches("<p>").count();
    assert!(
        p_count >= 1_000,
        "expected at least 1000 <p> tags, got {p_count}",
    );
}

// -----------------------------------------------------------------------------
// Unicode payloads
// -----------------------------------------------------------------------------

#[test]
fn markdown_unicode_title_and_body_round_trip_verbatim() {
    // Markdown is not HTML — escaping is NOT applied at the markdown
    // layer (the consumer's renderer escapes when it converts to HTML).
    // So a unicode payload must round-trip verbatim.
    let mut artifact = Artifact::new(
        "日本語タイトル — 中文标题 — العربية".into(),
        ArtifactType::Document,
        None,
    );
    artifact.update_content(
        "Emoji: \u{1F525} \u{1F3AF} \u{2764}\u{FE0F}\n\
         RTL: שלום עולם\n\
         Combining: e\u{0301} \u{1F468}\u{200D}\u{1F4BB}\n\
         CJK + math: 圆周率 π ≈ 3.14159\n"
            .into(),
    );

    let out = export_markdown(&artifact, &[]);
    assert!(out.contains("日本語タイトル"));
    assert!(out.contains("中文标题"));
    assert!(out.contains("العربية"));
    assert!(out.contains("\u{1F525}"));
    assert!(out.contains("\u{1F468}\u{200D}\u{1F4BB}"));
    assert!(out.contains("שלום עולם"));
    assert!(out.contains("e\u{0301}"));
    assert!(out.contains("圆周率 π ≈ 3.14159"));
    // Output must be valid UTF-8.
    assert!(
        std::str::from_utf8(out.as_bytes()).is_ok(),
        "markdown output must be valid UTF-8",
    );
}

#[test]
fn html_unicode_body_html_escapes_special_chars_but_keeps_non_ascii() {
    // The HTML exporter MUST escape `<`, `>`, `&`, `"`, `'` but MUST
    // preserve non-ASCII unicode literally — it's already valid
    // UTF-8 in the HTML body. A naive `escape_html` implementation
    // that lowercases or strips non-ASCII would fail this test.
    let mut artifact = Artifact::new("Unicode <Title>".into(), ArtifactType::Document, None);
    artifact.update_content("日本語 with <script> tag and & ampersand and \"quote\"".into());
    let out = export_html(&artifact, &[]);
    assert!(
        out.contains("日本語"),
        "unicode body must survive, got:\n{out}"
    );
    // Title rendered as <h1> — must NOT contain literal `<Title>`
    // (would mean it wasn't escaped).
    assert!(
        out.contains("Unicode &lt;Title&gt;"),
        "title must be escaped"
    );
    // Body's `<script>` must be escaped.
    assert!(
        out.contains("&lt;script&gt;"),
        "script tags in body must be escaped, got:\n{out}",
    );
    // `&` and `"` must be escaped.
    assert!(out.contains("&amp;"));
    assert!(out.contains("&quot;"));
    // The raw substring `<script>` (not escaped) must NOT appear in
    // the body (it's fine that we have `<style>`, `<title>` etc as
    // structural tags).
    assert!(
        !out.contains("<script>"),
        "raw <script> must not appear unescaped, got:\n{out}",
    );
}

#[test]
fn csv_unicode_title_with_embedded_quote_is_escaped_via_doubling() {
    // CSV requires `"` inside a quoted field to be doubled to `""`.
    // The artifact title contains a Unicode payload AND a quote.
    let artifact = Artifact::new(
        "日本語 \"quoted\" 標題".into(),
        ArtifactType::Document,
        None,
    );
    let out = export_csv(&artifact, &[]);
    assert!(out.contains("\"日本語 \"\"quoted\"\" 標題\""));
}

// -----------------------------------------------------------------------------
// Mermaid edge cases
// -----------------------------------------------------------------------------

#[test]
fn mermaid_adjacent_blocks_extract_independently() {
    // Two fenced blocks separated only by a single newline — the
    // extractor must surface BOTH, not merge them into one.
    let content =
        "```mermaid\nflowchart LR\nA-->B\n```\n```mermaid\npie\n\"A\" : 50\n\"B\" : 50\n```\n";
    let blocks = mermaid::extract_blocks(content);
    assert_eq!(blocks.len(), 2, "expected 2 blocks, got {blocks:?}");
    assert!(blocks[0].dsl.contains("flowchart"));
    assert!(blocks[1].dsl.contains("pie"));
    assert_eq!(blocks[0].diagram_type, "flowchart");
    assert_eq!(blocks[1].diagram_type, "pie");
}

#[test]
fn mermaid_block_at_very_start_of_content_extracts_cleanly() {
    let content = "```mermaid\nsequenceDiagram\nA->>B: hi\n```\nfollow-up text";
    let blocks = mermaid::extract_blocks(content);
    assert_eq!(blocks.len(), 1);
    assert_eq!(blocks[0].diagram_type, "sequence");
    assert!(blocks[0].dsl.contains("A->>B: hi"));
}

#[test]
fn mermaid_block_at_very_end_of_content_extracts_cleanly() {
    let content = "Prose text first.\n\n```mermaid\nstateDiagram\n[*] --> Idle\n```";
    let blocks = mermaid::extract_blocks(content);
    assert_eq!(blocks.len(), 1);
    assert_eq!(blocks[0].diagram_type, "state");
}

#[test]
fn mermaid_html_export_emits_one_div_per_block_and_one_runtime_script() {
    let content = "```mermaid\nflowchart LR\nA-->B\n```\n\nProse.\n\n```mermaid\npie\n\"X\" : 60\n\"Y\" : 40\n```\n";
    let mut artifact = Artifact::new("Two Diagrams".into(), ArtifactType::Document, None);
    artifact.update_content(content.into());
    let out = export_html(&artifact, &[]);

    // Each diagram must produce exactly one <div class="mermaid">.
    let div_count = out.matches(r#"<div class="mermaid""#).count();
    assert_eq!(
        div_count, 2,
        "expected 2 mermaid divs, got {div_count} in:\n{out}",
    );
    // The mermaid runtime script must be present exactly once (even
    // for multiple blocks).
    let runtime_count = out.matches("https://cdn.jsdelivr.net/npm/mermaid").count();
    assert_eq!(
        runtime_count, 1,
        "expected exactly 1 mermaid runtime script tag, got {runtime_count}",
    );
}

#[test]
fn mermaid_pdf_placeholder_strips_dsl_and_keeps_diagram_type() {
    let block = &mermaid::extract_blocks("```mermaid\nflowchart LR\nA-->B\n```\n")[0];
    let placeholder = mermaid::to_pdf_placeholder(block);
    assert!(
        !placeholder.contains("A-->B"),
        "PDF placeholder must NOT leak DSL, got: {placeholder}",
    );
    assert!(placeholder.contains("flowchart"));
}

#[test]
fn mermaid_markdown_round_trip_preserves_dsl_verbatim_via_to_markdown_block() {
    let original_dsl = "flowchart LR\n    A[Start] -->|next| B(Process)\n    B --> C{Done?}";
    let content = format!("```mermaid\n{original_dsl}\n```\n");
    let blocks = mermaid::extract_blocks(&content);
    assert_eq!(blocks.len(), 1);
    let round_tripped = mermaid::to_markdown_block(&blocks[0]);
    assert!(
        round_tripped.contains(original_dsl),
        "round-trip must preserve original DSL verbatim. Original:\n{original_dsl}\nGot:\n{round_tripped}",
    );
}

// -----------------------------------------------------------------------------
// Evidence pack edge cases
// -----------------------------------------------------------------------------

#[test]
fn evidence_pack_with_zero_citations_still_produces_valid_zip() {
    let dir = tempfile::tempdir().unwrap();
    let output = dir.path().join("evidence.zip");
    let artifact = Artifact::new("No Citations".into(), ArtifactType::Document, None);

    build_evidence_pack(&artifact, &[], output.to_str().unwrap()).expect("build_evidence_pack");

    let file = std::fs::File::open(&output).unwrap();
    let mut archive = zip::ZipArchive::new(file).expect("zip parses");
    let names: Vec<String> = (0..archive.len())
        .map(|i| archive.by_index(i).unwrap().name().to_string())
        .collect();
    assert!(names.contains(&"artifact.md".to_string()));
    assert!(names.contains(&"citations.json".to_string()));
    // No sources/ entries when there are no citations.
    assert!(
        !names.iter().any(|n| n.starts_with("sources/")),
        "expected no sources/ entries with 0 citations, got {names:?}",
    );
    // citations.json must contain an empty array.
    let mut buf = String::new();
    archive
        .by_name("citations.json")
        .unwrap()
        .read_to_string(&mut buf)
        .unwrap();
    let parsed: serde_json::Value = serde_json::from_str(&buf).expect("citations.json is JSON");
    assert!(
        parsed.is_array(),
        "citations.json must be an array, got {parsed:?}",
    );
    assert_eq!(parsed.as_array().unwrap().len(), 0);
}

#[test]
fn evidence_pack_dedupes_source_excerpts_across_repeated_source_ids() {
    // Two citations sharing the same SourceId — the per-source
    // excerpt files MUST be deduplicated to a single file. Without
    // the de-dup, the second iteration of the `start_file` call
    // would try to write a duplicate entry (some ZIP libraries
    // tolerate this; ours' guard against it).
    let shared_id = SourceId::new();
    let citations = vec![
        citation_for(shared_id, "Source Title", "First use"),
        citation_for(shared_id, "Source Title", "Second use"),
        citation_for(shared_id, "Source Title", "Third use"),
    ];
    let dir = tempfile::tempdir().unwrap();
    let output = dir.path().join("dedupe.zip");
    let artifact = Artifact::new("Dedup Test".into(), ArtifactType::Document, None);

    build_evidence_pack(&artifact, &citations, output.to_str().unwrap()).expect("build");

    let file = std::fs::File::open(&output).unwrap();
    let mut archive = zip::ZipArchive::new(file).expect("zip parses");
    let source_entries: Vec<String> = (0..archive.len())
        .map(|i| archive.by_index(i).unwrap().name().to_string())
        .filter(|n| n.starts_with("sources/"))
        .collect();
    assert_eq!(
        source_entries.len(),
        1,
        "expected exactly 1 sources/ entry for 3 citations sharing one SourceId, got {source_entries:?}",
    );
}

#[test]
fn evidence_pack_unicode_source_title_round_trips_through_excerpt() {
    let citation = citation_for(
        SourceId::new(),
        "日本語 source title — 中文标题 — العربية",
        "テスト目的",
    );
    let dir = tempfile::tempdir().unwrap();
    let output = dir.path().join("unicode.zip");
    let artifact = Artifact::new("ユニコード Test".into(), ArtifactType::Document, None);

    build_evidence_pack(
        &artifact,
        std::slice::from_ref(&citation),
        output.to_str().unwrap(),
    )
    .expect("build");

    let file = std::fs::File::open(&output).unwrap();
    let mut archive = zip::ZipArchive::new(file).expect("zip parses");
    let filename = format!("sources/{}.txt", citation.source_id);
    let mut buf = String::new();
    archive
        .by_name(&filename)
        .expect("source excerpt file exists")
        .read_to_string(&mut buf)
        .expect("source excerpt is UTF-8");
    assert!(
        buf.contains("日本語 source title — 中文标题 — العربية"),
        "unicode source title must survive, got:\n{buf}",
    );
    assert!(
        buf.contains("テスト目的"),
        "unicode used_for must survive, got:\n{buf}",
    );
}

#[test]
fn evidence_pack_artifact_md_includes_metadata_block_and_body() {
    let mut artifact = Artifact::new("With Body".into(), ArtifactType::Document, None);
    artifact.update_content("Body line 1.\nBody line 2.".into());
    let dir = tempfile::tempdir().unwrap();
    let output = dir.path().join("body.zip");
    build_evidence_pack(&artifact, &[], output.to_str().unwrap()).expect("build");

    let file = std::fs::File::open(&output).unwrap();
    let mut archive = zip::ZipArchive::new(file).expect("zip parses");
    let mut buf = String::new();
    archive
        .by_name("artifact.md")
        .unwrap()
        .read_to_string(&mut buf)
        .unwrap();
    assert!(buf.contains("# With Body"));
    assert!(buf.contains("Type: document"));
    // `Artifact::update_content` bumps the version from 1 to 2 as the
    // canonical sign that the artifact's body has been authored beyond
    // the initial empty state. We pin that the metadata block in
    // artifact.md surfaces the post-author version so an auditor
    // reading the evidence pack sees the same version number a sync
    // would report.
    assert!(
        buf.contains("Version: 2"),
        "expected post-update Version: 2 in metadata, got:\n{buf}",
    );
    assert!(buf.contains("Body line 1."));
    assert!(buf.contains("Body line 2."));
    // Section separator between metadata and body.
    assert!(
        buf.contains("\n---\n"),
        "artifact.md must include the `---` metadata/body separator, got:\n{buf}",
    );
}

#[test]
fn evidence_pack_many_citations_produces_one_excerpt_per_unique_source() {
    // 50 citations across 5 unique sources — expect exactly 5
    // sources/*.txt files.
    let mut citations = Vec::new();
    let source_ids: Vec<SourceId> = (0..5).map(|_| SourceId::new()).collect();
    for i in 0..50 {
        let sid = source_ids[i % 5];
        citations.push(citation_for(sid, "Doc", &format!("Use {i}")));
    }
    let dir = tempfile::tempdir().unwrap();
    let output = dir.path().join("many.zip");
    let artifact = Artifact::new("Many".into(), ArtifactType::Document, None);
    build_evidence_pack(&artifact, &citations, output.to_str().unwrap()).expect("build");

    let file = std::fs::File::open(&output).unwrap();
    let mut archive = zip::ZipArchive::new(file).expect("zip parses");
    let source_count = (0..archive.len())
        .filter(|&i| {
            archive
                .by_index(i)
                .is_ok_and(|f| f.name().starts_with("sources/"))
        })
        .count();
    assert_eq!(
        source_count, 5,
        "expected 5 unique source excerpts for 50 citations across 5 sources, got {source_count}",
    );
}
