//! In-process LLM inference via llama-cpp-2, replacing the
//! llama-server sidecar. Loads a GGUF model directly in the native
//! bridge and generates text without spawning an external process.

use std::sync::{Mutex, OnceLock};
use std::num::NonZeroU32;

use llama_cpp_2::context::params::LlamaContextParams;
use llama_cpp_2::llama_backend::LlamaBackend;
use llama_cpp_2::llama_batch::LlamaBatch;
use llama_cpp_2::model::params::LlamaModelParams;
use llama_cpp_2::model::{AddBos, LlamaModel};
use llama_cpp_2::sampling::LlamaSampler;

/// Holds the loaded model and context for in-process inference.
pub struct InferenceEngine {
    backend: LlamaBackend,
    model: LlamaModel,
}

static ENGINE: OnceLock<Mutex<Option<InferenceEngine>>> = OnceLock::new();

fn engine_slot() -> &'static Mutex<Option<InferenceEngine>> {
    ENGINE.get_or_init(|| Mutex::new(None))
}

/// Load a GGUF model file into memory. Replaces any previously loaded
/// model. Returns an error string on failure.
pub fn load_model(model_path: &str) -> Result<(), String> {
    let backend = LlamaBackend::init().map_err(|e| format!("Failed to init llama backend: {e}"))?;
    let params = LlamaModelParams::default();
    let model = LlamaModel::load_from_file(&backend, model_path, &params)
        .map_err(|e| format!("Failed to load model from {model_path}: {e}"))?;

    let mut slot = engine_slot().lock().map_err(|e| format!("Lock error: {e}"))?;
    *slot = Some(InferenceEngine { backend, model });
    Ok(())
}

/// Unload the current model, freeing memory.
pub fn unload_model() {
    if let Ok(mut slot) = engine_slot().lock() {
        *slot = None;
    }
}

/// Check whether a model is currently loaded.
pub fn is_model_loaded() -> bool {
    engine_slot()
        .lock()
        .map(|s| s.is_some())
        .unwrap_or(false)
}

/// Generation parameters passed from the JS side.
#[derive(Debug, Clone)]
pub struct GenerateParams {
    pub prompt: String,
    pub max_tokens: i32,
    pub temperature: f32,
}

/// A single token generated by the model, sent back to JS.
#[derive(Debug, Clone)]
pub struct GeneratedToken {
    pub token: String,
    pub done: bool,
}

/// Generate text from the loaded model, calling `on_token` for each
/// token produced. Returns the full completion text when done.
pub fn generate(
    params: GenerateParams,
    on_token: impl FnMut(GeneratedToken),
) -> Result<String, String> {
    let mut slot = engine_slot()
        .lock()
        .map_err(|e| format!("Lock error: {e}"))?;
    let engine = slot
        .as_mut()
        .ok_or("No model loaded — call load_model first")?;

    let ctx_params = LlamaContextParams::default()
        .with_n_ctx(NonZeroU32::new(4096))
        .with_n_batch(2048);
    let mut ctx = engine
        .model
        .new_context(&engine.backend, ctx_params)
        .map_err(|e| format!("Failed to create context: {e}"))?;

    let tokens = engine
        .model
        .str_to_token(&params.prompt, AddBos::Always)
        .map_err(|e| format!("Tokenization failed: {e}"))?;

    let mut batch = LlamaBatch::new(2048, 1);
    let last_index = tokens.len() as i32 - 1;
    for (i, token) in (0_i32..).zip(tokens.into_iter()) {
        let is_last = i == last_index;
        batch
            .add(token, i, &[0], is_last)
            .map_err(|e| format!("Batch add failed: {e}"))?;
    }
    ctx.decode(&mut batch)
        .map_err(|e| format!("Initial decode failed: {e}"))?;

    let mut n_cur = batch.n_tokens();
    let mut full_output = String::new();
    let mut on_token = on_token;

    let mut decoder = encoding_rs::UTF_8.new_decoder();

    let mut sampler = if params.temperature > 0.0 {
        LlamaSampler::chain_simple([
            LlamaSampler::temp(params.temperature),
            LlamaSampler::dist(0),
        ])
    } else {
        LlamaSampler::greedy()
    };

    let eos_token = engine.model.token_eos();
    let max_tokens = params.max_tokens.max(1);

    while n_cur <= max_tokens {
        let token = sampler.sample(&ctx, batch.n_tokens() - 1);
        sampler.accept(token);

        if token == eos_token {
            on_token(GeneratedToken {
                token: String::new(),
                done: true,
            });
            break;
        }

        let output_string = engine
            .model
            .token_to_piece(token, &mut decoder, true, None)
            .map_err(|e| format!("Token to piece failed: {e}"))?;

        full_output.push_str(&output_string);
        on_token(GeneratedToken {
            token: output_string,
            done: false,
        });

        batch.clear();
        batch
            .add(token, n_cur, &[0], true)
            .map_err(|e| format!("Batch add failed: {e}"))?;

        n_cur += 1;

        ctx.decode(&mut batch)
            .map_err(|e| format!("Decode failed: {e}"))?;
    }

    // If we didn't hit EOS, signal done
    if n_cur > max_tokens {
        on_token(GeneratedToken {
            token: String::new(),
            done: true,
        });
    }

    Ok(full_output)
}
