import "@testing-library/jest-dom/vitest";

const mockApi = {
  sources: {
    addLocalFolder: vi.fn().mockResolvedValue({
      id: "src-1",
      sourceType: "local_folder",
      path: "/mock/folder",
      status: "connected",
      createdAt: new Date().toISOString(),
      lastIndexed: null,
      fileCount: 0,
    }),
    addLocalFile: vi.fn().mockResolvedValue({
      id: "src-2",
      sourceType: "local_file",
      path: "/mock/file.md",
      status: "connected",
      createdAt: new Date().toISOString(),
      lastIndexed: null,
      fileCount: 1,
    }),
    listSources: vi.fn().mockResolvedValue([]),
    removeSource: vi.fn().mockResolvedValue(undefined),
    searchSources: vi.fn().mockResolvedValue([]),
  },
  artifacts: {
    create: vi.fn().mockResolvedValue({
      id: "art-1",
      title: "Test Artifact",
      artifactType: "document",
      templateId: null,
      content: "",
      citations: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
    }),
    update: vi.fn(),
    list: vi.fn().mockResolvedValue([]),
    get: vi.fn(),
    remove: vi.fn(),
    exportArtifact: vi.fn(),
    generateFromTemplate: vi.fn().mockResolvedValue({
      id: "art-2",
      title: "Generated",
      artifactType: "document",
      templateId: "prd-v1",
      content: "",
      citations: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
    }),
    extractTasksDecisions: vi.fn().mockResolvedValue([]),
    compareSources: vi.fn().mockResolvedValue({
      id: "art-compare",
      title: "Compare",
      artifactType: "document",
      templateId: null,
      content: "",
      citations: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
    }),
    exportEvidencePack: vi.fn().mockResolvedValue("/tmp/pack.zip"),
  },
  connectors: {
    status: vi.fn().mockResolvedValue({
      provider: "google_drive",
      connected: false,
    }),
    authenticate: vi.fn().mockResolvedValue({
      provider: "google_drive",
      connected: true,
    }),
    disconnect: vi.fn().mockResolvedValue(undefined),
    selectItems: vi.fn().mockResolvedValue([]),
    syncDrive: vi.fn().mockResolvedValue([]),
  },
  templates: {
    list: vi.fn().mockResolvedValue([]),
    get: vi.fn().mockResolvedValue(null),
  },
  settings: {
    get: vi.fn().mockResolvedValue({
      theme: "light",
      defaultExportFormat: "markdown",
      ignorePatterns: [".git", "node_modules"],
      watchPatterns: ["**/*.md"],
    }),
    update: vi.fn().mockResolvedValue({
      theme: "light",
      defaultExportFormat: "markdown",
      ignorePatterns: [".git", "node_modules"],
      watchPatterns: ["**/*.md"],
    }),
  },
  model: {
    status: vi.fn().mockResolvedValue({
      available: false,
      modelName: null,
      status: "not_configured",
    }),
    start: vi.fn().mockResolvedValue(undefined),
    stop: vi.fn().mockResolvedValue(undefined),
    generate: vi.fn().mockResolvedValue(undefined),
    cancelJob: vi.fn().mockResolvedValue(undefined),
    onToken: vi.fn().mockReturnValue(() => undefined),
  },
  dialog: {
    showSaveDialog: vi.fn().mockResolvedValue({ canceled: true }),
  },
  runtime: {
    detectPlatform: vi.fn().mockResolvedValue({
      platform: "linux-x64",
      platformLabel: "Linux x64",
      totalRamGb: 16,
      tier: "high",
      tierLabel: "High (8+ GB RAM)",
      computeBackends: ["cpu"],
      preferredFormat: "gguf",
    }),
    recommendModel: vi.fn().mockResolvedValue(null),
    listModels: vi.fn().mockResolvedValue([]),
    getCurrentModel: vi.fn().mockResolvedValue(null),
    planDownload: vi.fn().mockResolvedValue({
      kind: "direct-download",
      modelId: "ternary-bonsai-1.7b-gguf",
      filename: "ternary-bonsai-1.7b-q1_0_g128.gguf",
      downloadSizeMb: 450,
      message: "Download Ternary-Bonsai 1.7B (450 MB).",
    }),
    downloadModel: vi.fn(),
    deleteModel: vi.fn().mockResolvedValue(undefined),
    onDownloadProgress: vi.fn().mockReturnValue(() => undefined),
  },
};

Object.defineProperty(window, "tessera", {
  value: mockApi,
  writable: true,
});
